version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: jwt_postgres
    environment:
      POSTGRES_DB: jwt_db
      POSTGRES_USER: jwt_user
      POSTGRES_PASSWORD: jwt_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - jwt_network

  app:
    build: .
    container_name: jwt_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jwt_db
      SPRING_DATASOURCE_USERNAME: jwt_user
      SPRING_DATASOURCE_PASSWORD: jwt_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - jwt_network

volumes:
  pg_data:

networks:
  jwt_network:
